name: Validate Vocabs on PRs to Develop
on:
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Bring in repo - source branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Verify checked-out branch
        run: echo "Checked out branch - ${{ github.head_ref }}"
      - name: Install UV and Prezmanifest
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv tool install prezmanifest
      - name: Validate all vocabs with Prezmanifest
        run: |
          pm validate manifest.ttl
